---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: opxhub/build
inputs:
- name: src
outputs:
- name: dist
run:
  path: bash
  args:
  - -ec
  - |
    # workaround for hard-coded /mnt directory in opx_build script
    cp -r src /mnt/src
    # build packages
    pushd /mnt/
    /opt/opx-build/scripts/opx_build src
    popd
    # copy artifacts to output
    cp -t dist/ /mnt/*.deb /mnt/*.build /mnt/*.dsc /mnt/*.tar.gz

